### ISSUE TITLE
Incorrect configuration example for apps.json

### ISSUE THREAD

**Issue by prathikvel** [phntxx/dashboard#14]
The configuration example for `apps.json` shows `"URL"` instead of the updated `"url"`. This isn't a major issue, but it confused me when I installed Dashboard.

By the way, I'm loving Dashboard so far. Great work!

**Comment by phntxx** [comment]
And that is why you don't make massive "change everything at once"-commits. There's always something you forget.
Thank you very much for noticing and letting me know 😄
I also very much appreciate your compliments; I love it when people actually like the stuff I put out

I fixed it now, closing
