### ISSUE TITLE
[Search] Default search provider

### ISSUE THREAD

**Issue by erlenmeyer316** [phntxx/dashboard#17]
Is there any way to set the default search provider through configuration? 

The use case would be that I want to have search, but I only want one search provider, say Qwant. However I don't want to have to use a search prefix, Just type in the search bar and hit enter?

**Comment by phntxx** [comment]
Hi,

this is currently not possible. I've started implementing this a couple of days ago and will update the app once I'm ready.

**Comment by phntxx** [comment]
I merged this into main yesterday. To utilize this feature, make sure your `search.json` looks like this:

```
{
"defaultprovider": "https://test.test?q=",
"providers": [
...
]
}
```

closing.
