### ISSUE TITLE
Settings button appears only briefly when loading, then disappears

### ISSUE THREAD

**Issue by MaxBayly** [phntxx/dashboard#24]
I was trying to create and use a theme, however I am unable to change it - I assume that the settings button is required for this. However, it only appears briefly while the page is loading and is unclickable, then disappears. 

More info: Running in Docker on Debian, access in Chromium and Firefox, same behaviour with an empty or populated apps list

**Comment by phntxx** [comment]
Hi!

This sounds very odd to me.
I've set it up so that the settings menu button only shows up when either `themes.json` or `search.json` or both could be loaded.

It'd be great if you could answer the following two questions for me:

What are the contents of your `data`-directory exactly (the one with all of the json files in it)?
Can you verify that your `themes.json` is valid JSON and reflects the one in the `README`?

My personal guess would be that there's something wrong with your `themes.json` file.

Kind regards
Bastian Meissner

**Comment by MaxBayly** [comment]
This is the contents of my data directory:
`apps.json  bookmarks.json.disabled  docker-compose.yml  greeter.json  themes.json`

And this is the structure of my themes.json:
```
{
  "themes": [
    {
      "label": "test",
      "value": "1",
      "mainColor": "#666666",
      "accentColor": "#FF0000",
      "backgroundColor": "#00FF00"
    }
  ]
}
```
To my eye this reflects what's in the README, but I could be missing something.

I'm also not seeing anything useful in the web console, but I don't really know what I'm looking for

**Comment by phntxx** [comment]
Out of interest: Try replacing `"value": "1",` with `"value": 0,`. Other than that I'm unsure as to what causes this behaviour. I'll look into it some more.

**Comment by MaxBayly** [comment]
Still no luck. Let me know if there's any other information you need to help, I'll do my best to provide it

**Comment by yrangana** [comment]
did you check the themes.json file? The same happened when themes file got issues.
can you replace themes.json file with [themes.json](https://raw.githubusercontent.com/phntxx/dashboard/master/data/themes.json) and check ?

**Comment by MaxBayly** [comment]
As mentioned earlier in the discussion, the themes.json was already validated. That example also yielded no solution

**Comment by thedeany** [comment]
@MaxBayly In your earlier comment you don't mention a `search.json` file existing in your `data` directory. This would cause the issue of the flashing settings icon (as the search's defaults exist on first render until the app attempts to get the contents of the file, which in your case appears to not exist.)

**Comment by MaxBayly** [comment]
So if I understand correctly, the ability to switch themes depends on enabling search providers as well? Is there an example of `search.json` anywhere? I couldn't manage to find any, and I don't really understand the example given

**Comment by thedeany** [comment]
While currently the only _configurable_ setting within the settings panel is the theme, the settings panel also shows the available search engines as well as your default search engine. You can find examples of the necessary files at the top-level `data` directory in this repo. [Here's a link](https://github.com/phntxx/dashboard/blob/master/data/search.json) to `search.json`.

**Comment by MaxBayly** [comment]
Cheers for that. Unfortunately, still no luck, not too sure what's going on

**Comment by thedeany** [comment]
Any errors or warnings in the devtools console?

**Comment by thedeany** [comment]
Actually now that I look at the repo, it looks like phntxx did a fairly major refactor last night. After a quick look at the changes, I think the latest version of the app should fix the issues you're seeing.

**Comment by MaxBayly** [comment]
Just managed to run the new image and everything is looking good. Seems like the refactor worked its magic!

**Comment by thedeany** [comment]
Glad to hear it!
