### ISSUE TITLE
error Command "serve:production" not found.

### ISSUE THREAD

**Issue by maxwassiljew** [phntxx/dashboard#26]
➜ yarn serve:production
yarn run v1.22.10
error Command "serve:production" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by phntxx** [comment]
Yes, I removed that option a while back. I'll add it back in.

Kind regards
Bastian

**Comment by phntxx** [comment]
Should be back in now.
