### ISSUE TITLE
Settings goes off the top of the screen on mobile

### ISSUE THREAD

**Issue by cinderblockgames** [phntxx/dashboard#43]
Using the provided theme and search options, opening settings by clicking on the (very small) cog centers the modal vertically on the first view height, which puts the top off the screen.  You can scroll down to see the bottom, but there's no way to scroll up past the top of the page.  The settings modal should start no higher than the top of the page.

**Comment by cinderblockgames** [comment]
The [most recent commit](https://github.com/phntxx/dashboard/commit/eb5cb2dee67f5a69908c6fdcf92e7ece8a8abd2f) reverts the [fix for this](https://github.com/phntxx/dashboard/pull/45).

**Comment by phntxx** [comment]
Darn, didn't notice that. I'll push out a fix later today.

**Comment by cinderblockgames** [comment]
Thanks for fixing!
