### ISSUE TITLE
Icon font requires external resources

### ISSUE THREAD

**Issue by Qu4tro** [phntxx/dashboard#6]
Hey :wave: 

Currently the font used to display icons is fetched through gstatic.
This is normally fine, but if you're using `NoScript` religiously or if you're not connected to the internet, no icons will show up.
My suggestion is to also bundle the font when running `yarn build`.

Thanks!

**Comment by phntxx** [comment]
Hi

Sounds like a reasonable idea, I'll look into it.

Kind regards

**Comment by phntxx** [comment]
Terribly sorry I'm only getting back to this just now. I've switched over to writing my own icon library since, using the official Material.io icon font. Could you perhaps elaborate on what you mean when bundling the font when running `yarn build`?

Kind regards

**Comment by phntxx** [comment]
Hi,

I've done a quick rewrite a couple of days ago. Now all required fonts are bundled in with the image and stored locally. I hope this fixes this issue.

Closing.

**Comment by Qu4tro** [comment]
Amazing. Thank you! 

And let me just apologise for the lack of a reply. I intended to, but I postponed the first time and the tab likely got pushed into my never ending bookmark stack.
